jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      sudo apt-get -qq update
      sudo apt-get install -y curl wget nasm make gcc g++ build-essential qemu-system-x86 qemu-system-aarch86 util-linux
      lscpu
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
      export PATH=$PATH:~/.cargo/bin
      cargo install cargo-xbuild
      rustup component add rust-src
      rustup component add llvm-tools-preview
      rustup target add aarch64-unknown-linux-gnu
      cargo install bootimage
      make
      make qemu
      make arch=aarch64
      make arch=aarch64 qemu
    displayName: 'Test eduOS-rs on Ubuntu 16.04'
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
      export PATH=$PATH:$HOME/.cargo/bin
      cargo install cargo-xbuild
      rustup component add rust-src
      rustup component add llvm-tools-preview
      cargo install bootimage
      brew install qemu
      make
      make qemu
    displayName: 'Test eduOS-rs on macOS'
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain nightly
      echo ##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin
      choco install qemu make --limit-output --no-progress
      echo ##vso[task.setvariable variable=PATH;]%PATH%;C:\Program Files\qemu
      set PATH=%PATH%;C:\Program Files\qemu
      cargo install cargo-xbuild
      rustup component add rust-src
      rustup component add llvm-tools-preview
      cargo install bootimage
      make
      make qemu
    displayName: 'Test eduOS-rs on Windows'

